# Generated by Django 3.2.4 on 2022-10-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0005_country_is_active'),
        ('vendor', '0008_auto_20221001_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendor.customuser')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('phone_number', models.CharField(max_length=16, verbose_name='phone number')),
                ('avatar', models.ImageField(default='profile.png', upload_to='media/Customer-Avatar/')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.country')),
            ],
        ),
    ]
