# Generated by Django 3.2.4 on 2022-10-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_country_is_active'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.country'),
        ),
    ]
