# Generated by Django 3.2.4 on 2022-10-23 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_wishitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='id',
        ),
        migrations.AddField(
            model_name='wishitem',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
