# Generated by Django 3.2.4 on 2022-10-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20221023_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
