# Generated by Django 3.2.4 on 2022-10-01 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20221001_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
