# Generated by Django 3.2.4 on 2022-10-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(unique=True, upload_to='media/Products-Avatar/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/Products-Avatar/'),
        ),
    ]
