# Generated by Django 3.2.4 on 2022-10-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
