# Generated by Django 3.2.4 on 2022-10-02 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productvariation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='id',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
