# Generated by Django 3.2.4 on 2022-10-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
