# Generated by Django 3.2.4 on 2022-10-04 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='dealoftheday',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealoftheday',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 5, 57, 52, 201211, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealoftheday',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealoftheday',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_products', to='product.Tag'),
        ),
    ]
