# Generated by Django 3.2.4 on 2022-10-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20221004_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealoftheday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
