# Generated by Django 3.2.4 on 2022-10-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20221020_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.UUIDField()),
                ('days', models.IntegerField(default=1)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
