# Generated by Django 3.2.4 on 2022-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_remove_product_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
