# Generated by Django 3.2.4 on 2022-10-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_product_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsalerequest',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
