# Generated by Django 3.2.4 on 2022-10-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_rename_approved_flashsalerequest_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsalerequest',
            name='product',
        ),
    ]
