# Generated by Django 3.2.4 on 2022-10-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_flashsalerequest_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsalerequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='product.product'),
        ),
    ]
