# Generated by Django 3.2.4 on 2022-10-20 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_flashsalerequest_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsalerequest',
            name='id',
        ),
        migrations.AddField(
            model_name='flashsalerequest',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
