# Generated by Django 3.2.4 on 2022-10-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20221020_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsale',
            name='product',
        ),
    ]
