# Generated by Django 3.2.4 on 2022-10-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
