# Generated by Django 3.2.4 on 2022-10-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_flashsale_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
