# Generated by Django 3.2.4 on 2022-10-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_auto_20221025_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsalerequest',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
