# Generated by Django 3.2.4 on 2022-10-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='condition',
            field=models.CharField(choices=[('newbies', 'newbies'), ('orders', 'orders'), ('amount', 'amount'), ('category', 'category'), ('shipping', 'shipping')], max_length=20),
        ),
    ]
