# Generated by Django 3.2.4 on 2022-11-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('coupons', '0004_alter_coupon_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='condition',
            field=models.CharField(choices=[('newbies', 'newbies'), ('orders', 'orders'), ('amount', 'amount'), ('product', 'product'), ('shipping', 'shipping')], max_length=20),
        ),
    ]
