# Generated by Django 3.2 on 2022-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='uid',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
