# Generated by Django 3.2 on 2022-09-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_paymentmethods_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='branch_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='uid',
            field=models.CharField(max_length=255),
        ),
    ]
