# Generated by Django 3.2.4 on 2022-10-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220930_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
