# Generated by Django 3.2.4 on 2022-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_saleincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleincome',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('refunded', 'refunded')], default='pending', max_length=10),
        ),
    ]
