# Generated by Django 3.2.4 on 2022-10-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_paymentmethods_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethods',
            name='id',
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='uid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
