# Generated by Django 3.2.4 on 2022-10-05 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_auto_20221005_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethods',
            name='id',
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
