# Generated by Django 3.2 on 2022-09-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0005_vendor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendor.customuser')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=4)),
                ('tel', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
