# Generated by Django 3.2.4 on 2022-10-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='shipping_zones',
            field=models.ManyToManyField(blank=True, related_name='countries', to='administrator.ShippingFeeZone'),
        ),
    ]
