# Generated by Django 3.2.4 on 2022-10-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_country_shipping_zones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='shipping_zones',
        ),
    ]
