# Generated by Django 3.2 on 2022-09-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
