# Generated by Django 3.2.4 on 2022-10-28 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_remove_country_shipping_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='shipping_zones',
            field=models.ManyToManyField(blank=True, related_name='countries', to='administrator.ShippingFeeZone'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
