# Generated by Django 3.2.4 on 2022-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_country_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField()),
                ('location', models.TextField()),
                ('coordinates', models.JSONField()),
                ('image', models.ImageField(upload_to='media/Site-Addresses/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('phone_number', models.TextField()),
                ('site_email', models.EmailField(max_length=254)),
                ('note', models.TextField()),
                ('addresses', models.ManyToManyField(blank=True, to='administrator.SiteAddress')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
