# Generated by Django 3.2.4 on 2022-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_siteconfiguration_site_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
