# Generated by Django 3.2.4 on 2022-10-05 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_siteaddress_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
