# Generated by Django 3.2.4 on 2022-10-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20221005_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='phone number'),
        ),
    ]
