# Generated by Django 3.2.4 on 2022-10-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_alter_administrator_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='has_states',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='country',
            name='states',
            field=models.ManyToManyField(blank=True, to='administrator.State'),
        ),
    ]
