# Generated by Django 3.2.4 on 2022-10-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20221007_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='id',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='country',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='state',
            name='shipping_fee',
        ),
    ]
