# Generated by Django 3.2.4 on 2022-10-07 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_auto_20221007_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingFeeZone',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='shipping_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='administrator.shippingfeezone'),
        ),
        migrations.AddField(
            model_name='state',
            name='shipping_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='states', to='administrator.shippingfeezone'),
        ),
    ]
