# Generated by Django 3.2.4 on 2022-10-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20221007_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='states',
        ),
    ]
