# Generated by Django 3.2.4 on 2022-10-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_auto_20221007_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='states',
            field=models.ManyToManyField(blank=True, to='administrator.State'),
        ),
    ]
