# Generated by Django 3.2.4 on 2022-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_country_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='has_states',
        ),
        migrations.RemoveField(
            model_name='country',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='country',
            name='states',
        ),
        migrations.AddField(
            model_name='country',
            name='shipping_zones',
            field=models.ManyToManyField(related_name='countries', to='administrator.ShippingFeeZone'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
