# Generated by Django 3.2.4 on 2022-10-21 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_auto_20221007_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('header', models.CharField(max_length=1000)),
                ('sub_header', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/Banners/')),
                ('btn_link', models.CharField(max_length=1000)),
                ('btn_text', models.CharField(max_length=1000)),
                ('btn_color', models.CharField(max_length=255)),
                ('btn_text_color', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
