# Generated by Django 3.2.4 on 2022-10-23 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='id',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
