# Generated by Django 3.2.4 on 2022-10-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_socialmedia_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='working_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
