# Generated by Django 3.2.4 on 2022-10-26 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='id',
        ),
        migrations.AddField(
            model_name='visitor',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
