# Generated by Django 3.2.4 on 2022-10-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_auto_20221026_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='appstore_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='playstore_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
