# Generated by Django 3.2.4 on 2022-10-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_auto_20221027_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='appstore_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='playstore_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
    ]
