# Generated by Django 3.2.4 on 2022-10-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_auto_20221027_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingfeezone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
