# Generated by Django 3.2.4 on 2022-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_shippingfeezone_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
