# Generated by Django 3.2.4 on 2022-11-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_auto_20221101_0124'),
        ('order', '0005_auto_20221101_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='coupons.Coupon'),
        ),
    ]
