# Generated by Django 3.2.4 on 2022-11-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_auto_20221101_0124'),
        ('order', '0006_alter_order_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupons',
        ),
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon'),
        ),
    ]
