# Generated by Django 3.2.4 on 2022-11-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20221101_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupons',
            new_name='coupon_used',
        ),
    ]
