# Generated by Django 3.2.4 on 2022-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitem_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
