# Generated by Django 3.2.4 on 2022-10-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20221005_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='arrived_date',
            new_name='cancelled_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refunded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
