# Generated by Django 3.2.4 on 2022-11-01 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='id',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
