# Generated by Django 3.2.4 on 2022-10-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='8KAWF870J', max_length=15),
        ),
    ]
