# Generated by Django 3.2.4 on 2022-10-27 22:25

from django.db import migrations, models
import order.utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=order.utils.generate_order_id, editable=False, max_length=15),
        ),
    ]
