# Generated by Django 3.2.4 on 2022-11-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_shippingaddress_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county',
            new_name='country',
        ),
    ]
