# Generated by Django 3.2.4 on 2022-11-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20221102_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
